use strict;
use warnings;
use Test::More;

# Set dummy environment variables
BEGIN {
    $ENV{DB_TABLE}    = 'test_table';
    $ENV{DB_HOST}     = 'localhost';
    $ENV{DB_NAME}     = 'feedback';
    $ENV{DB_PASSWORD} = 'password';
    $ENV{ASANA_TOKEN} = 'dummy';
    $ENV{ASANA_PROJECT} = '123';
}

# Load script
require '/tmp/scripts/report_to_asana.pl';

# Mimick report structure generated by the real script
subtest 'Calculation Logic' => sub {
    my $report = {
        positive => 1,
        negative => 3,
        total    => 4,
    };
    
    # Calculate percentages exactly exactly as the real script
    my $pos_pct = sprintf("%.2f%%", ($report->{positive} / $report->{total}) * 100);
    my $neg_pct = sprintf("%.2f%%", ($report->{negative} / $report->{total}) * 100);

    is($pos_pct, '25.00%', 'Positive percentage is correct');
    is($neg_pct, '75.00%', 'Negative percentage is correct');
};

# Note Generation
subtest 'Note Formatting' => sub {
    my $mock_report = {
        total        => 10,
        positive     => 7,
        positive_pct => '70.00%',
        negative     => 3,
        negative_pct => '30.00%',
    };

    my $output = generate_notes($mock_report);

    # Ensure the string contains the key data points
    like($output, qr/Total Comments: 10/, 'Output has total count');
    like($output, qr/Positive: 7 \(70\.00%\)/, 'Output has positive stats');
    like($output, qr/====================/, 'Output has separator lines');
};

done_testing();
